#!/bin/sh
# Called by sxiv(1) after any unbound key is pressed.
# The key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.
# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

# En mode image, l'action n'est appliquée qu'à l'image active ; en mode
# vignette, elle est au contraire appliquée à toutes les images marquées.

case "$1" in
    "e")
        while read file; do exif_data=$(exiv2 -q -ps -- "$file"); dunstify -r 4739 -t 3000 "$exif_data"; done ;;
    "C-Delete")
        while read file; do rm "$file"; done ;;
    "C-c")
        while read file; do filetype=$(file -b --mime-type "$file") && xclip -selection clipboard -t $filetype -i "$file"; done ;;
    "C-underscore")
        while read file; do mogrify -flip "$file"; done ;;
    "C-bar")
        while read file; do mogrify -flop "$file"; done ;;
    "C-L")
        while read file; do mogrify -rotate -90 "$file"; done ;;
    "C-R")
        while read file; do mogrify -rotate +90 "$file"; done ;;
    "C-t")
        xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
esac
