#!/bin/sh
# Pour qu'une action s'applique à toutes les images marquées, il faut
# l'inclure dans une boucle ; par exemple :
# while read file; do mogrify -rotate 90 "$file"; done ;;

case "$1" in
    "C-c")
        filetype=$(file -b --mime-type "$file") && xclip -selection clipboard -t $filetype -i $file ;;
    "C-t")
        xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
    "C-Delete")
        rm "$file" ;;
    "C-L")
        mogrify -rotate -90 "$file" ;;
    "C-R")
        mogrify -rotate +90 "$file" ;;
esac
